"""add_daily_scores

Revision ID: 2e5f3a6b1c9d
Revises: 5b7362f1a9d4
Create Date: 2026-03-25 16:30:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2e5f3a6b1c9d'
down_revision = '5b7362f1a9d4'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('global_score', sa.Integer(), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=False),
    sa.Column('activity_score', sa.Integer(), nullable=False),
    sa.Column('routine_score', sa.Integer(), nullable=False),
    sa.Column('autonomy_score', sa.Integer(), nullable=False),
    sa.Column('baseline_similarity', sa.Integer(), nullable=False),
    sa.Column('main_factors', sa.JSON(), nullable=False),
    sa.Column('narrative_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_scores_id'), 'daily_scores', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_scores_id'), table_name='daily_scores')
    op.drop_table('daily_scores')
    # ### end Alembic commands ###
