"""verify_checkin_analysis

Revision ID: 3a42987e8804
Revises: 7a9b0c1d2e3f
Create Date: 2026-03-24 13:05:27.366001

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '3a42987e8804'
down_revision = '7a9b0c1d2e3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_in_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('detected_signals', sa.JSON(), nullable=False),
    sa.Column('recommended_action', sa.String(length=500), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_check_in_analysis_id'), 'check_in_analysis', ['id'], unique=False)
    op.add_column('notification_jobs', sa.Column('provider_response', sa.Text(), nullable=True))
    op.add_column('notification_jobs', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_jobs', 'last_attempt_at')
    op.drop_column('notification_jobs', 'provider_response')
    op.drop_index(op.f('ix_check_in_analysis_id'), table_name='check_in_analysis')
    op.drop_table('check_in_analysis')
    # ### end Alembic commands ###