"""Add last_triggered_at to scheduled reminders

Revision ID: 51f0981624e7
Revises: 58be1a304ee9
Create Date: 2026-03-26 12:35:15.516124

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '51f0981624e7'
down_revision = '58be1a304ee9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_reminders', schema=None) as batch_op:
        batch_op.drop_column('last_triggered_at')

    # ### end Alembic commands ###