"""add_user_baseline_profiles

Revision ID: 5b7362f1a9d4
Revises: 3a42987e8804
Create Date: 2026-03-25 15:45:00.000000

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5b7362f1a9d4'
down_revision = '3a42987e8804'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_baseline_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usual_mood', sa.String(length=20), nullable=False),
    sa.Column('usual_activity_level', sa.String(length=20), nullable=False),
    sa.Column('usual_energy_level', sa.String(length=20), nullable=False),
    sa.Column('lives_alone', sa.Boolean(), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.Column('usual_sleep_hours', sa.Float(), nullable=False),
    sa.Column('social_interaction_level', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_baseline_profiles_id'), 'user_baseline_profiles', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_baseline_profiles_id'), table_name='user_baseline_profiles')
    op.drop_table('user_baseline_profiles')
    # ### end Alembic commands ###
