"""sync_check_in_analysis_model

Revision ID: 8139c5faa13b
Revises: 2e5f3a6b1c9d
Create Date: 2026-03-25 16:29:11.749461

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8139c5faa13b'
down_revision = '2e5f3a6b1c9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_in_analysis', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('check_in_analysis', sa.Column('mood', sa.String(length=20), nullable=False))
    op.add_column('check_in_analysis', sa.Column('signals', sa.JSON(), nullable=False))
    op.add_column('check_in_analysis', sa.Column('risk', sa.String(length=20), nullable=False))
    op.drop_column('check_in_analysis', 'source_text')
    op.drop_column('check_in_analysis', 'detected_signals')
    op.drop_column('check_in_analysis', 'recommended_action')
    op.drop_column('check_in_analysis', 'risk_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_in_analysis', sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('check_in_analysis', sa.Column('recommended_action', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('check_in_analysis', sa.Column('detected_signals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('check_in_analysis', sa.Column('source_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('check_in_analysis', 'risk')
    op.drop_column('check_in_analysis', 'signals')
    op.drop_column('check_in_analysis', 'mood')
    op.drop_column('check_in_analysis', 'text')
    # ### end Alembic commands ###