"""add_interpretation_to_daily_score

Revision ID: a1d7ae9e3f78
Revises: 8139c5faa13b
Create Date: 2026-03-25 16:49:39.823484

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a1d7ae9e3f78'
down_revision = '8139c5faa13b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_scores', sa.Column('interpretation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_scores', 'interpretation')
    # ### end Alembic commands ###