"""add_user_interpretation_settings

Revision ID: a9cef39897d3
Revises: a1d7ae9e3f78
Create Date: 2026-03-26 12:05:31.962994

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a9cef39897d3'
down_revision = 'a1d7ae9e3f78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interpretation_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sensitivity_mode', sa.String(length=20), nullable=False),
    sa.Column('has_chronic_pain', sa.Boolean(), nullable=False),
    sa.Column('low_energy_baseline', sa.Boolean(), nullable=False),
    sa.Column('mood_variability', sa.Boolean(), nullable=False),
    sa.Column('low_communication', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_interpretation_settings')
    # ### end Alembic commands ###