from __future__ import annotations

"""add profile_image_url to user

Revision ID: cac2555e5b8f
Revises: 51f0981624e7
Create Date: 2026-03-27 13:33:43.309580

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'cac2555e5b8f'
down_revision = '51f0981624e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspect_obj = sa.inspect(conn)
    
    # Check daily_scores table
    ds_cols = [c['name'] for c in inspect_obj.get_columns('daily_scores')]
    if 'observed_routines' not in ds_cols:
        op.add_column('daily_scores', sa.Column('observed_routines', sa.JSON(), nullable=True))
    if 'missed_or_late_routines' not in ds_cols:
        op.add_column('daily_scores', sa.Column('missed_or_late_routines', sa.JSON(), nullable=True))
        
    # Check users table
    u_cols = [c['name'] for c in inspect_obj.get_columns('users')]
    if 'profile_image_url' not in u_cols:
        op.add_column('users', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_url')
    op.drop_column('daily_scores', 'missed_or_late_routines')
    op.drop_column('daily_scores', 'observed_routines')
    # ### end Alembic commands ###