"""add_fcm_token_to_frontend_users

Revision ID: e729e354ef9c
Revises: cac2555e5b8f
Create Date: 2026-04-13 14:01:44.227354

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e729e354ef9c'
down_revision = 'cac2555e5b8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frontend_users', sa.Column('fcm_token', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frontend_users', 'fcm_token')
    # ### end Alembic commands ###